language: go
go:
- 1.4.2
sudo: false

# Grab newest version and suck down
install:
    - export FILE=go_appengine_sdk_linux_amd64-$(curl https://appengine.google.com/api/updatecheck | grep release | grep -o '[0-9\.]*').zip
    - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
    - unzip -q $FILE

# Run build and tests
script:
    - ./go_appengine/goapp get golang.org/x/tools/cmd/cover
    - ./go_appengine/goapp test -test.v=true
    - ./go_appengine/goapp test -cover -test.v=true -test.coverprofile=c.out
    - ./go_appengine/goapp build
